### ISSUE TITLE
Port to Gradle

### ISSUE THREAD

**Issue by niftynei** [orbotix/Sphero-Android-SDK#10]
I noticed that your instructions include using the Eclipse plugin.  Is there any interest, need for this to be ported to Gradle, for use with Android Studio?  

Or has someone done this already? x D

**Comment by zenelk** [comment]
I have a tutorial for setting up the new sample in the beta SDK for Android Studio / Gradle. The current one on master will not be upgraded for Gradle / Android Studio.

Internally, we have actually moved over to Android Studio for our development, so future projects should come out with Gradle support.
