### ISSUE TITLE
Location permission required for connecting to Sphero on Android 6

### ISSUE THREAD

**Issue by hunyadym** [orbotix/Sphero-Android-SDK#16]
On Android 6, you can only read the HW address of nearby Bluetooth devices if the app has ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permissions (https://developer.android.com/intl/es/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id).

Therefore, the Sphero app can't connect to the Sphero balls on Android 6.0 (I found this problem using Nexus 5, 7 and 9s), and also the apps using this SDK can't connect without this permission. After adding this permission to my app, it could connect to the Sphero. (The app previously worked on Android 5.1 without any problem on the same devices.)

**Comment by Whateverest** [comment]
+1 ! Im having the same problem on my Nexus 5.

**Comment by Kristina-Simakova** [comment]
I have the same problem here, Nexus 5 and Nexus 7 with Android M

**Comment by useyourblues** [comment]
How do I add this permission to the Sphero app?

**Comment by PaulTR** [comment]
The official Sphero app has been updated. Updated samples are coming out soon. For your own programs you will just need to include the location permission in your manifest, and make sure you request it during runtime if you target API 23+.
