### ISSUE TITLE
DiscoveryAgentClassic not disconnecting Sphero.

### ISSUE THREAD

**Issue by akm0012** [orbotix/Sphero-Android-SDK#18]
I am trying to create a program that can connect to Sphero, then once connected the user can press a sleep button to put Sphero to sleep (while disconnecting). Once disconnected, the app will restart the Sphero Search.  

However, `DiscoveryAgentClassic.getInstance().getConnectedRobots().size() > 0` this statement is always returning true before I call `DiscoveryAgentClassic.getInstance().startDiscovery(main_activity_context);`

So the above statement is returning false due to this error state. "Connecting or Connected robots count is already at max" I checked and the max is 1.  

I have tried disconnecting the Sphero many times and in many different ways to no avail.  Normally I cache the robot and call `sphero.sleep()` which puts the Sphero in standby, but the SDK still thinks I am connected. 

I've tried `DiscoveryAgentClassic.getInstance().disconnectAll();`

and 

`if (DiscoveryAgentClassic.getInstance().getConnectedRobots().size() > 0) {
            Robot badBoy = DiscoveryAgentClassic.getInstance().getConnectedRobots().get(0);
            if (badBoy != null) {
                badBoy.disconnect();
            }
        }`

Nothing is working and this is preventing me from restarting my Sphero search. 

Any help would be awesome!

- Andrew

**Comment by PaulTR** [comment]
Can you toss your code onto GIT somewhere so I can check it out? If you're calling discover/connect before the robot is fully disconnected, that may be causing an issue, but I'd want to confirm before I give you wrong advice :)

**Comment by PaulTR** [comment]
Closing due to a month of no response.
