### ISSUE TITLE
My app can search Ollie,but can not connect Ollie

### ISSUE THREAD

**Issue by SamYangzx** [orbotix/Sphero-Android-SDK#19]
I program an app for Ollie by SDK 3.1.159. I install it on my Coolpad phone, it can connect the Ollie.
But I install it on my another Phone, it can not connect the Ollie. I watch the log, the app has search the  
Ollie, but it can not connect Ollie? Can you open the source of RobotLibrary.jar ? or  tell me how to solve this problem ?

**Comment by PaulTR** [comment]
What is your other phone that isn't connecting? If it connects on one phone, it should connect to the other. There are some weird issues with different devices/manufacturer implementations of Bluetooth LE, but I'd want to verify on that phone before I give you a solid answer.

**Comment by PaulTR** [comment]
Closing after a month of no response.
