### ISSUE TITLE
Does this SDK work on BB-8??

### ISSUE THREAD

**Issue by slo424** [orbotix/Sphero-Android-SDK#20]
I have managed to follow the samples and connect to SPRK and Ollie.

I have thought that the way to connect to BB-8 is similar to how it's done with Ollie, but no luck...
Any idea how it should be done??

**Comment by iamcgn** [comment]
Hi @slo424, thanks for reaching out about our SDK. Unfortunately we are not able to open up our Android SDK to connect to BB-8. We want to ensure the authenticity of BB-8 the character that you see on screen.
