### ISSUE TITLE
Can't find my BB-8 from Nexus 5X (Android 6.0 Marshmallow)

### ISSUE THREAD

**Issue by mach** [orbotix/Sphero-Android-SDK#21]
The log:

```
D/BluetoothAdapter: startLeScan(): null
```

I guess `startLeScan()` is not working on Android 6.0.

Using [BluetoothLeScanner](http://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html) instead might solve the problem.

**Comment by PaulTR** [comment]
At this time BB-8 is not connectable through our SDK, so that may be a part of the issue. If you have an Ollie by chance, that should connect, but if you can put your sample app up on GitHub I can check against one if you don't and I can see if there's maybe something else going on.

**Comment by PaulTR** [comment]
Also you may want to make sure Location Services are enabled on your device if you haven't already. As of Marshmallow, Bluetooth requires Location Services (as well as location permissions) to operate because beacons are lumped in with BLE support.

**Comment by mach** [comment]
@PaulTR Thank you.

I've granted ACCESS_COARSE_LOCATION permission to my Nexus 5X on run time, and I can find the BB-8 by calling [startScan()](http://developer.android.com/intl/ja/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(android.bluetooth.le.ScanCallback)) manually (not using Sphero SDK).

But somehow I cannot find it by [startLeScan()](http://developer.android.com/intl/ja/reference/android/bluetooth/BluetoothAdapter.html#startLeScan(android.bluetooth.BluetoothAdapter.LeScanCallback)), which is deprecated in API level 21. That's why I think the problem is related to `startLeScan()` itself on Marshmallow.

**Comment by PaulTR** [comment]
Yeah I'm not sure. If it's not something in our SDK, then I haven't checked into it.

**Comment by mach** [comment]
Your SDK is using [startLeScan()](http://developer.android.com/intl/ja/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(android.bluetooth.le.ScanCallback)) for scanning Sphero devices.

I mean, replacing [startLeScan()](http://developer.android.com/intl/ja/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(android.bluetooth.le.ScanCallback)) to [startScan()](startScan()) on Marshmallow could fix this problem.

If you open the source of RobotLibrary.jar, I can test it and make a pull request.

**Comment by PaulTR** [comment]
RobotLibrary isn't going to be open sourced :) I'll check into it on Tuesday. Either way, the BB-8 won't be connectable with the SDK.

**Comment by mach** [comment]
Thank you!

> Either way, the BB-8 won't be connectable with the SDK.

But why? @orbotix 's official JavaScript SDK supports BB-8, and not on Android?
https://github.com/orbotix/sphero.js

**Comment by adamajohnston** [comment]
@mach 

BB-8s are named differently from Ollies. If you use the LE discovery agent directly instead of DualStackDiscoveryAgent you can set the name prefix ('BB-' in the case of BB-8s) in the RadioDescriptor directly. i.e.
```
    private void startDiscovery() {
        mDiscoveryAgent = DiscoveryAgentLE.getInstance();
        mDiscoveryAgent.addDiscoveryListener(this);
        mDiscoveryAgent.addRobotStateListener(this);

        RobotRadioDescriptor robotRadioDescriptor = new RobotRadioDescriptor();
        robotRadioDescriptor.setNamePrefixes(new String[]{"BB-"});
        mDiscoveryAgent.setRadioDescriptor(robotRadioDescriptor);

        try {
            mDiscoveryAgent.startDiscovery(this);
        } catch (DiscoveryException e) {
            Log.e("Sphero", "Discovery Error: " + e);
            e.printStackTrace();
        }
    }

    @Override
    public void handleRobotsAvailable(List<Robot> robots) {
        Log.i("Sphero", "Found " + robots.size() + " robots");

        for (Robot robot : robots) {
            Log.i("Sphero", "  " + robot);
            mDiscoveryAgent.connect(robot);
        }
    }

    @Override
    public void handleRobotChangedState(Robot robot, RobotChangedStateNotificationType robotChangedStateNotificationType) {
        switch (robotChangedStateNotificationType) {
            case Online:
                Log.i("Sphero", "Robot " + robot.getName() + " Online!");
                // Do stuff with robot here
            case Connecting:
                Log.i("Sphero", "Robot " + robot.getName() + " Connecting!");
                break;
            case Connected:
                Log.i("Sphero", "Robot " + robot.getName() + " Connected!");
                break;
            // Handle other cases
        }
    }

```

03-06 13:32:16.413 14055-14055/com.adamj.bb8test I/Sphero: Discovery Started
03-06 13:32:17.139 14055-14055/com.adamj.bb8test I/Sphero: Robot BB-D179 Connecting!
03-06 13:32:17.144 14055-14055/com.adamj.bb8test I/Sphero: Discovery Stopped
03-06 13:32:17.144 14055-14055/com.adamj.bb8test I/Sphero: Found 1 robots
03-06 13:32:17.145 14055-14055/com.adamj.bb8test I/Sphero:   BB-D179
03-06 13:32:17.742 14055-14055/com.adamj.bb8test I/Sphero: Robot BB-D179 Connected!
03-06 13:32:18.497 14055-14055/com.adamj.bb8test I/Sphero: Robot BB-D179 Online!

**Comment by mahditaleb** [comment]
setRadioDescriptor not set!

**Comment by mahditaleb** [comment]
thanks

**Comment by mpvillafranca** [comment]
Following the @adamajohnston code I have created an app to successfully connect with the Sphero BB-8. Thank you mate, let's se what I can do with this baby now! :smiley:

**Comment by marcusletric** [comment]
I struggled so much with adroid SDK to connect BB8 without success.
Thanks @adamajohnston
