### ISSUE TITLE
can't connect BB-8?

### ISSUE THREAD

**Issue by Hirohisa-Miyazaki** [orbotix/Sphero-Android-SDK#27]
Are these samples applicable to BB-8?
It seems programs cant not find BB-8 by bluetooth.

**Comment by zenelk** [comment]
Hey @Hirohisa-Miyazaki. Unfortunately we are not able to open up our Android SDK to connect to BB-8. We want to ensure the authenticity of BB-8 the character that you see on screen.

**Comment by marcusletric** [comment]
Hmmm, but on NodeJS you could drive BB8.

I feel deviation in the force....
