### ISSUE TITLE
Unable to get it to connect with examples to a sprk+

### ISSUE THREAD

**Issue by chibill** [orbotix/Sphero-Android-SDK#29]
^ Not even the samples work.

**Comment by scottpantall** [comment]
Which example are you trying to run? The only one that shouldn't work is the Drive Sample app and I have a pull request submitted for that problem.

**Comment by chibill** [comment]
I  can't get any of them to do anything. (Even the HelloWorld sample does nothing)

I am also not sure how to tell if it is even connected.

**Comment by scottpantall** [comment]
Are you able to get the HelloWorld app installed on your phone?

**Comment by chibill** [comment]
Sort of. I had to move its code into a valid Android Project... (The current build.gradle with it does not work)

**Comment by scottpantall** [comment]
Do you know anything about Gradle? I didn't until I started playing with the Sphero Android apps. I'm still not sure I really understand it.

 Here's a link to my activity log where I threw in some links about Gradle to help understand it: 
[https://github.com/scottpantall/Updated-Sphero-DriveSample/wiki/Activity-Log](https://github.com/scottpantall/Updated-Sphero-DriveSample/wiki/Activity-Log)

I hope that helps some. Gradle seems like it's as useful as it is hard to figure out. I'll see if I can break my sample apps sometime in the next few days to see if I can help out more.

**Comment by chibill** [comment]
I understand gradle. (I used it for modding minecraft a bit) I just got it to compile with out modifications. After building with my Android Studio.. Testing again.

**Comment by zenelk** [comment]
@chibill Did you open the samples you were trying by using import in Android Studio or were you attempting to open them a different way? Also, is this on the beta branch or master?

**Comment by chibill** [comment]
The master branch and Android studio would not even see them.

**Comment by zenelk** [comment]
Yep. Looks like the samples on master are totally broken. Sorry about that. If possible, can you use the beta branch? That will be moved into master soon, and I just verified that you can open the samples using import in Android Studio.

**Comment by chibill** [comment]
Okay. I will try the beta branch. (I am working on an app to basically be a bridge between the Sphero (sprk+) and my laptop.

**Comment by chibill** [comment]
OKAY! The beta samples work! Thanks for all your help!

**Comment by chibill** [comment]
On a side note the sensor-stream app does not currently work.

**Comment by zenelk** [comment]
Just fixed and pushed it up to beta. Feel free to open more issues if you find anything else.
