### ISSUE TITLE
No proper docs for the Android SDK

### ISSUE THREAD

**Issue by chibill** [orbotix/Sphero-Android-SDK#30]
There is no documentation on how to use the current version of the SDK. (And docs link links to an IOS docs)

**Comment by zenelk** [comment]
We are currently in the process of getting the newest update finalized, which includes the updates to the documentation. The docs on sdk.sphero.com are for the version that is on master right now, but are still pretty close to that which is on the beta branch, so you could attempt to use those in the mean time. You can change the language using the buttons in the upper right of that docs page from the default (which is objc) to Android.

**Comment by chibill** [comment]
Ohh.. I never noticed the buttons...
