### ISSUE TITLE
Connect To Sprk+

### ISSUE THREAD

**Issue by tswapnil** [orbotix/Sphero-Android-SDK#32]
The sample code doesn't connect to Sphero Sprk+ . I think the RoboticLibrary.jar needs to be updated .

**Comment by nateswartz** [comment]
@tswapnil Have you tried the beta branch?  I encountered the same issue, and was able to connect to a Sprk+ with a Fire HD 6 tablet using the RoboticLibrary.jar from the beta branch.

**Comment by tswapnil** [comment]
Thanks. I was able to use the beta branch code.
