### ISSUE TITLE
leaked IntentReceiver orbotix.robot.base.RobotProvider

### ISSUE THREAD

**Issue by lemonnm** [orbotix/Sphero-Android-SDK#9]
Hi,

When i try the project helloWorld i had this error :
HelloWorldActivity has leaked IntentReceiver orbotix.robot.base.RobotProvider$1@41f2eb10 that was originally registered here. Are you missing a call to unregisterReceiver()?

With log : 
HelloWorld﹕ Found: [[Robot: Sphero-BOR @68:86:E7:01:C4:12 connected=false]]
HelloWorld﹕ Found 1 robots

I word with Android Studio and nexus 7 2012 with Android 4.4

Thx,

Matthieu

**Comment by zenelk** [comment]
I am closing this as it should be fixed by the beta SDK. Please open a new issue if the problem persists on the beta branch.
